version: '3.4'

services:

  # The Java bot process -- uses Dockerfile in ./docker/docker-bot
  # Will attempt to restart 3 times.
  # Depends on __Config.toml__ for startup config
  bot:
    image: ib.ai
    restart: on-failure:3
    build: ./bot/docker
    container_name: bot
    env_file:
      - ./env/bot.env
    depends_on:
      - db

  # Experimental
  # Will always restart on crash.
  # All /web/ files are volumes in Docker container, including config.
  #web:
  #  image: web
  #  restart: always
  #  build: ./web/docker
  #  container_name: web
  #  volumes:
  #    - ./web:/usr/src/app
  #  ports:
  #    - 5001:80
  #  depends_on:
  #    - db

  # Redis database
  # Running on port 6379, on a failure it will restart itself
  # Depends on __redis.conf__ for startup config.
  # Connect via the URL 'redis://db:6379'
  db:
    restart: always
    image: redis
    container_name: db
    command: redis-server /opt/IB.ai/Redis.conf
    volumes:
      - ./db/Redis.conf:/opt/IB.ai/Redis.conf
    ports:
      - 6379:6379
