version: '3.4'

services:

  # The Java bot process -- uses Dockerfile in ./docker/docker-bot
  # Will attempt to restart 3 times.
  # Depends on __Config.toml__ for startup config
  bot:
    image: ib.ai
    restart: on-failure:3
    build: ./IB.ai/docker
    container_name: bot
    volumes:
      - ./IB.ai/docker/Config.toml:/opt/IB.ai/Config.toml
    networks:
      - bot-db-net
    depends_on:
      - db

  # Experimental
  # Will always restart on crash.
  # All /web/ files are volumes in Docker container, including config.
  web:
    image: web
    restart: always
    build: ./web/docker
    container_name: web
    volumes:
      - ./web/:/usr/src/app
    networks:
      - bot-db-net
    ports:
      - "80"
    environment:
      WEB_URL: "http://web:80"
    depends_on:
      - db

  # Redis database
  # Running on port 6379, on a failure it will restart itself
  # Depends on __redis.conf__ for startup config.
  # Connect via the URL 'db:{PORT}'
  db:
    restart: always
    image: redis
    container_name: db
    command: redis-server /opt/IB.ai/Redis.conf
    volumes:
      - ./database-config/Redis.conf:/opt/IB.ai/Redis.conf
    networks:
      - bot-db-net
    ports:
      - "6379"
    environment:
      DB_URL: "http://db:6379"

networks:
  bot-db-net:
    driver: bridge
